/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Desain;

/**
 *
 * @author DIKA
 */
public class FrHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrHome.class.getName());

    /**
     * Creates new form FrHome
     */
public FrHome() {
        initComponents();
        mulaiJam();

        // 1. SET UKURAN DEFAULT: Terbuka sebagai jendela kecil (800 x 500 px)
        this.setSize(800, 500);

        // 2. AKTIFKAN RESIZE: Tombol Maximize di pojok kanan atas aktif
        this.setResizable(true);

        // 3. POSISI TENGAH: Selalu muncul tepat di tengah layar monitor saat dibuka
        this.setLocationRelativeTo(null);

        // 4. OTOMATISASI RESPONSIF: Jika ditarik / di-maximize,
        //    seluruh form di dalamnya otomatis melar rapi dengan margin simetris 10px
        jDesktopPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                int margin = 10; // Jarak gap simetris dari bingkai luar
                for (javax.swing.JInternalFrame f : jDesktopPane1.getAllFrames()) {
                    f.setBounds(
                        margin, 
                        margin, 
                        jDesktopPane1.getWidth() - (margin * 2), 
                        jDesktopPane1.getHeight() - (margin * 2)
                    );
                }
            }
        });

        // Mencegah error jika dijalankan langsung tanpa login
        if (Core.Session.getStatus() == null) {
            lblUser.setText("User : Belum Login");
            return;
        }

        // Menampilkan nama asli dan role di status bar
        lblUser.setText("User : " + Core.Session.getNama() + " (" + Core.Session.getStatus() + ")");

        // Logika Hak Akses Berdasarkan Role
        if ("kasir".equalsIgnoreCase(Core.Session.getStatus()) || "petugas".equalsIgnoreCase(Core.Session.getStatus())) {
            btnDataKendaraan.setVisible(false);
            btnDataPelanggan.setVisible(true);
            menuMaster.setVisible(false);
        } else {
            btnDataKendaraan.setVisible(true);
            btnDataPelanggan.setVisible(true);
            menuMaster.setVisible(true);
        }
    }

    /**
     * Method Tunggal Membuka Form Internal
     * Menjaga margin & ukuran 100% simetris & responsif di semua menu
     */
    public void bukaForm(javax.swing.JInternalFrame frame) {
        jDesktopPane1.removeAll(); // Hapus form lama

        // Format margin & warna via FormUtils
        Desain.FormUtils.formatFrame(frame);

        jDesktopPane1.add(frame);

        // Atur posisi & ukuran dengan margin 10px dari tepi jDesktopPane1
        int margin = 10;
        frame.setBounds(
            margin, 
            margin, 
            jDesktopPane1.getWidth() - (margin * 2), 
            jDesktopPane1.getHeight() - (margin * 2)
        );

        frame.setVisible(true);
        jDesktopPane1.revalidate();
        jDesktopPane1.repaint();
    }

    /**
     * Listener Jam Real-time
     */
    private void mulaiJam() {
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                java.util.Date waktuSekarang = new java.util.Date();

                java.text.SimpleDateFormat formatJam = new java.text.SimpleDateFormat("HH:mm:ss");
                lblJam.setText(formatJam.format(waktuSekarang));

                java.text.SimpleDateFormat formatTanggal = new java.text.SimpleDateFormat("dd-MM-yyyy");
                lblTanggal.setText(formatTanggal.format(waktuSekarang));
            }
        });
        timer.start();
    }
    // -------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        btnDataKendaraan = new javax.swing.JButton();
        btnProsesSewa = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnDataPelanggan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        menuMaster = new javax.swing.JMenu();
        menuDataKendaraan = new javax.swing.JMenuItem();
        menuDataPelanggan = new javax.swing.JMenuItem();
        menuDataPetugas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuProsesSewa = new javax.swing.JMenuItem();
        menuProsesPengembalian = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCetakLaporan = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(8, 107, 115));

        btnDataKendaraan.setText("DATA KENDARAAN");
        btnDataKendaraan.addActionListener(this::btnDataKendaraanActionPerformed);

        btnProsesSewa.setText("PROSES SEWA");
        btnProsesSewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProsesSewaMouseClicked(evt);
            }
        });
        btnProsesSewa.addActionListener(this::btnProsesSewaActionPerformed);

        jButton3.setText("PENGEMBALIAN");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(this::jButton3ActionPerformed);

        btnDataPelanggan.setText("DATA PELANGGAN");
        btnDataPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDataPelangganMouseClicked(evt);
            }
        });
        btnDataPelanggan.addActionListener(this::btnDataPelangganActionPerformed);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnDataKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDataPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProsesSewa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDataKendaraan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDataPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnProsesSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(8, 107, 115));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jam :");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal:");

        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("User : ");

        lblJam.setForeground(new java.awt.Color(255, 255, 255));
        lblJam.setText("00:00:00");

        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setText("--/--/----");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJam)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTanggal)
                .addGap(26, 26, 26)
                .addComponent(lblUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(lblUser)
                    .addComponent(lblJam)
                    .addComponent(lblTanggal))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        menuLogout.setText("Logout");
        menuLogout.addActionListener(this::menuLogoutActionPerformed);
        jMenu1.add(menuLogout);

        menuExit.setText("Exit");
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        menuMaster.setText("Master");

        menuDataKendaraan.setText("Data Kendaraan");
        menuDataKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDataKendaraanMouseClicked(evt);
            }
        });
        menuDataKendaraan.addActionListener(this::menuDataKendaraanActionPerformed);
        menuMaster.add(menuDataKendaraan);

        menuDataPelanggan.setText("Data Pelanggan");
        menuDataPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDataPelangganMouseClicked(evt);
            }
        });
        menuDataPelanggan.addActionListener(this::menuDataPelangganActionPerformed);
        menuMaster.add(menuDataPelanggan);

        menuDataPetugas.setText("Data Petugas");
        menuDataPetugas.addActionListener(this::menuDataPetugasActionPerformed);
        menuMaster.add(menuDataPetugas);

        jMenuBar1.add(menuMaster);

        jMenu4.setText("Transaksi");

        menuProsesSewa.setText("Proses Sewa");
        menuProsesSewa.addActionListener(this::menuProsesSewaActionPerformed);
        jMenu4.add(menuProsesSewa);

        menuProsesPengembalian.setText("Proses Pengembalian");
        menuProsesPengembalian.addActionListener(this::menuProsesPengembalianActionPerformed);
        jMenu4.add(menuProsesPengembalian);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Laporan");

        menuCetakLaporan.setText("Cetak Laporan");
        menuCetakLaporan.addActionListener(this::menuCetakLaporanActionPerformed);
        jMenu2.add(menuCetakLaporan);

        jMenuItem1.setText("Riwayat Sewa");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
// 1. Hapus data sesi (session)
    Core.Session.setIdPetugas(null);
    Core.Session.setNama(null);
    Core.Session.setStatus(null);
    
    // 2. Buka kembali form Login
    Desain.FrLogin login = new Desain.FrLogin();
    login.setVisible(true);
    
    // 3. Tutup form Home ini
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void btnDataKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataKendaraanActionPerformed
bukaForm(new FrKendaraan());
    // formKendaraan.setLocationRelativeTo(null); // Agar muncul di tengah layar        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataKendaraanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
bukaForm(new FrKembali());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void menuProsesSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProsesSewaActionPerformed
// Membuat wujud dari form FrSewa
FrSewa formSewa = new FrSewa();

// Memasukkan formSewa ke dalam area JDesktopPane yang ada di FrHome
jDesktopPane1.add(formSewa);

// Menampilkan formnya agar bisa dilihat
formSewa.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuProsesSewaActionPerformed

    private void btnProsesSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesSewaActionPerformed
 bukaForm(new FrSewa());     // TODO add your handling code here:
    }//GEN-LAST:event_btnProsesSewaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
Desain.FrRiwayat formRiwayat = new Desain.FrRiwayat();
    jDesktopPane1.add(formRiwayat);
    formRiwayat.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuDataKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataKendaraanActionPerformed
Desain.FrKendaraan formKendaraan = new Desain.FrKendaraan();
    jDesktopPane1.add(formKendaraan); // jDesktopPane1 adalah nama area biru Anda
    formKendaraan.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuDataKendaraanActionPerformed

    private void menuProsesPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProsesPengembalianActionPerformed
Desain.FrKembali formKembali = new Desain.FrKembali();
    jDesktopPane1.add(formKembali);
    formKembali.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuProsesPengembalianActionPerformed

    private void menuDataPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataPetugasActionPerformed
  // Memanggil form FrPetugas
    Desain.FrPetugas formPetugas = new Desain.FrPetugas();
    
    // Menambahkan form ke dalam area biru (jDesktopPane1)
    jDesktopPane1.add(formPetugas); 
    
    // Menampilkan form
    formPetugas.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_menuDataPetugasActionPerformed

    private void menuDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataPelangganActionPerformed
    Desain.FrPelanggan formPelanggan = new Desain.FrPelanggan();
    jDesktopPane1.add(formPelanggan);
    formPelanggan.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_menuDataPelangganActionPerformed

    private void btnDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPelangganActionPerformed
    bukaForm(new FrPelanggan());    // TODO add your handling code here:
    }//GEN-LAST:event_btnDataPelangganActionPerformed

    private void btnProsesSewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProsesSewaMouseClicked
try {
    // 1. Panggil form internal Anda (Contoh: FrSewa)
    FrSewa formSewa = new FrSewa();
    jDesktopPane1.add(formSewa); // Sesuaikan nama JDesktopPane Anda
    formSewa.setVisible(true);
    
    // 2. Perintah agar JInternalFrame otomatis memenuhi seluruh area JDesktopPane
    formSewa.setMaximum(true); 
    
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka form: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnProsesSewaMouseClicked

    private void btnDataPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataPelangganMouseClicked
      try {
        // Ganti FrPelanggan dengan nama class form pelanggan Anda
        FrPelanggan formPelanggan = new FrPelanggan();
        jDesktopPane1.add(formPelanggan);
        formPelanggan.setVisible(true);
        formPelanggan.setMaximum(true); // Agar otomatis fullscreen di desktop pane
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka form: " + e.getMessage());
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btnDataPelangganMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
     try {
        // Ganti FrPengembalian dengan nama class form pengembalian Anda
        FrKembali formPengembalian = new FrKembali();
        jDesktopPane1.add(formPengembalian);
        formPengembalian.setVisible(true);
        formPengembalian.setMaximum(true); // Agar otomatis fullscreen di desktop pane
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka form: " + e.getMessage());
    }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void menuDataPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDataPelangganMouseClicked
    try {
        FrPelanggan formPelanggan = new FrPelanggan();
        jDesktopPane1.add(formPelanggan);
        formPelanggan.setVisible(true);
        
        // Memastikan ukuran desktop pane sudah siap dibaca sebelum form diatur ukurannya
        javax.swing.SwingUtilities.invokeLater(() -> {
            formPelanggan.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        });
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka form: " + e.getMessage());
    } // TODO add your handling code here:
    }//GEN-LAST:event_menuDataPelangganMouseClicked

    private void menuDataKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDataKendaraanMouseClicked
try {
        FrKendaraan formKendaraan = new FrKendaraan();
        jDesktopPane1.add(formKendaraan);
        formKendaraan.setVisible(true);
        formKendaraan.setMaximum(true);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka form: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_menuDataKendaraanMouseClicked

    private void menuCetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCetakLaporanActionPerformed
     // 1. Tampilkan form FrRiwayat ke dalam JDesktopPane
    Desain.FrRiwayat fr = new Desain.FrRiwayat();
    jDesktopPane1.removeAll(); // Sesuaikan 'jDesktopPane1' dengan nama variabel JDesktopPane Anda
    jDesktopPane1.add(fr);
    fr.setVisible(true);

    // 2. Langsung jalankan fungsi cetak
    fr.cetakLaporanPDF();   // TODO add your handling code here:
    }//GEN-LAST:event_menuCetakLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataKendaraan;
    private javax.swing.JButton btnDataPelanggan;
    private javax.swing.JButton btnProsesSewa;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuItem menuCetakLaporan;
    private javax.swing.JMenuItem menuDataKendaraan;
    private javax.swing.JMenuItem menuDataPelanggan;
    private javax.swing.JMenuItem menuDataPetugas;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuProsesPengembalian;
    private javax.swing.JMenuItem menuProsesSewa;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
