/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Desain;

/**
 *
 * @author DIKA
 */
public class FrKendaraan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrKendaraan
     */
    public FrKendaraan() {
        initComponents();
        // KUNCI SIMETRIS: Memberi margin dalam (Atas: 15px, Kiri: 20px, Bawah: 25px, Kanan: 20px)
    ((javax.swing.JComponent) getContentPane()).setBorder(
        javax.swing.BorderFactory.createEmptyBorder(15, 20, 25, 20)
    );
        tampilTable();
        this.getContentPane().setBackground(new java.awt.Color(0, 210, 196));this.getContentPane().setBackground(new java.awt.Color(0, 210, 196));
        try {
        this.setMaximum(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
    }
    private void tampilTable() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("No. Polisi");
        model.addColumn("Merk Kendaraan");
        model.addColumn("Jenis");
        model.addColumn("Harga Sewa");
        model.addColumn("Status"); 
        
        try {
            java.sql.Connection conn = new myConnection.DB0().getConnection();
            java.sql.Statement st = conn.createStatement();
            String sql = "SELECT * FROM tb_kendaraan";
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nopol"),
                    rs.getString("merk_kendaraan"),
                    rs.getString("jenis"),
                    rs.getString("harga_sewa"),
                    rs.getString("status")
                });
            }
            tbKendaraan.setModel(model); 
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtMerk = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtPlat = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbKendaraan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        jTextField2.setText("jTextField1");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setBorder(null);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor" }));
        cbJenis.addActionListener(this::cbJenisActionPerformed);

        tbKendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKendaraanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbKendaraan);

        jLabel2.setText("Merk  :");

        jLabel3.setText("Harga Sewa  :");

        jLabel4.setText("Plat Nomor  :");

        jLabel5.setText("Jenis  :");

        jPanel1.setOpaque(false);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear);

        btnUpdate.setText("UPDATE");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel1.add(btnUpdate);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        jPanel1.add(btnSimpan);

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel1.add(btnHapus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addComponent(txtHarga)
                            .addComponent(txtPlat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMerk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbJenis, javax.swing.GroupLayout.Alignment.TRAILING, 0, 354, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
try {
    // Validasi agar tidak ada kotak yang kosong
    if (txtPlat.getText().isEmpty() || txtMerk.getText().isEmpty() || txtHarga.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua data harus diisi terlebih dahulu!");
        return;
    }

    String jenis = cbJenis.getSelectedItem().toString();
    
    // Query Insert disesuaikan dengan nama kolom asli di phpMyAdmin
    String sql = "INSERT INTO tb_kendaraan (nopol, merk_kendaraan, jenis, harga_sewa, status) VALUES ('" 
            + txtPlat.getText() + "', '" 
            + txtMerk.getText() + "', '" 
            + jenis + "', '" 
            + txtHarga.getText() + "', 'Tersedia')";
    
    int i = Core.DML.EQuery(sql);
    
    if (i > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data Kendaraan Berhasil Disimpan!");
        
        // Kosongkan form setelah berhasil
        txtPlat.setText("");
        txtMerk.setText("");
        txtHarga.setText("");
        cbJenis.setSelectedIndex(0);
        
        // Refresh tabel
        tampilTable(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data! (Kemungkinan Plat Nomor sudah terdaftar)");
    }
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}     // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tbKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKendaraanMouseClicked
try {
    int baris = tbKendaraan.getSelectedRow();
    if (baris != -1) {
        txtPlat.setText(tbKendaraan.getValueAt(baris, 0).toString());
        txtMerk.setText(tbKendaraan.getValueAt(baris, 1).toString());
        cbJenis.setSelectedItem(tbKendaraan.getValueAt(baris, 2).toString());
        txtHarga.setText(tbKendaraan.getValueAt(baris, 3).toString());
        
        // Kunci Plat Nomor (karena nopol adalah Primary Key) agar tidak bisa diubah saat mode update
        txtPlat.setEnabled(false); 
    }
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_tbKendaraanMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
  // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
     txtPlat.setText("");
    txtMerk.setText("");
    txtHarga.setText("");
    cbJenis.setSelectedIndex(0);
    txtPlat.setEditable(true); // Buka kembali kunci plat nomor
    tbKendaraan.clearSelection();   // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
     try {
        if (txtPlat.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data dari tabel yang akan dihapus!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus kendaraan ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM tb_kendaraan WHERE nopol = '" + txtPlat.getText() + "'";
            Core.DML.EQuery(sql);
            javax.swing.JOptionPane.showMessageDialog(this, "Data Kendaraan Berhasil Dihapus!");
            
            btnClearActionPerformed(evt);
            tampilTable();
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
     try {
        if (txtPlat.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data dari tabel yang akan diubah!");
            return;
        }

        String sql = "UPDATE tb_kendaraan SET merk = '" + txtMerk.getText() 
                + "', jenis = '" + cbJenis.getSelectedItem().toString() 
                + "', harga = " + txtHarga.getText() 
                + " WHERE nopol = '" + txtPlat.getText() + "'";

        Core.DML.EQuery(sql);
        javax.swing.JOptionPane.showMessageDialog(this, "Data Kendaraan Berhasil Diubah!");
        
        btnClearActionPerformed(evt); // Reset form
        tampilTable(); // Refresh tabel
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + e.getMessage());
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tbKendaraan;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtPlat;
    // End of variables declaration//GEN-END:variables
}
