/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Desain;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author DIKA
 */
public class FrKembali extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrKembali
     */
    public FrKembali() {
        initComponents();
    // 1. HILANGKAN HEADER ABU-ABU & IKON PANAH
    javax.swing.plaf.basic.BasicInternalFrameUI ui = 
        (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
    ui.setNorthPane(null);
    ((javax.swing.JComponent) getContentPane()).setBorder(
        javax.swing.BorderFactory.createEmptyBorder(15, 20, 25, 20)
    );

    // 2. HILANGKAN BORDER/GARIS PINGGIR ABU-ABU
    this.setBorder(null);

    // Kode warna & tampil tabel yang sudah ada sebelumnya
    this.getContentPane().setBackground(new java.awt.Color(0, 210, 196));
        this.getContentPane().setBackground(new java.awt.Color(0, 210, 196));
        try {
        this.setMaximum(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
        tampilTable();
    }
    public void tampilTable() {
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("ID Sewa");
    model.addColumn("NIK");
    model.addColumn("Nopol");
    model.addColumn("Tgl Sewa");
    model.addColumn("Durasi");
    model.addColumn("Total Harga");

    try {
        // Menggunakan koneksi database yang sama dengan FrKendaraan
        java.sql.Connection conn = new myConnection.DB0().getConnection();
        java.sql.Statement st = conn.createStatement();
        
        // Ambil data transaksi yang statusnya MASIH 'Sedang Disewa'
        String sql = "SELECT * FROM tb_sewa WHERE status_sewa = 'Sedang Disewa'";
        java.sql.ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_sewa"),
                rs.getString("nik"),
                rs.getString("nopol"),
                rs.getString("tgl_sewa"),
                rs.getString("durasi"),
                rs.getString("total_harga")
            });
        }
        tbPengembalian.setModel(model);
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data pengembalian: " + e.getMessage());
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtIdTransaksi = new javax.swing.JTextField();
        lblIDTrk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDenda = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPengembalian = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblIDTrk.setText("ID Transaksi");

        jLabel1.setText("Denda");

        txtDenda.setText("0");

        btnProses.setText("PROSES PENGEMBALIAN");
        btnProses.addActionListener(this::btnProsesActionPerformed);

        tbPengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPengembalianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPengembalian);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIDTrk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdTransaksi)
                            .addComponent(btnProses, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                            .addComponent(txtDenda))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDTrk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
int row = tbPengembalian.getSelectedRow();
    if (row == -1 || txtIdTransaksi.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih transaksi dari tabel yang akan dikembalikan!");
        return;
    }

    try {
        String idSewa = txtIdTransaksi.getText();
        String nopol = tbPengembalian.getValueAt(row, 2).toString();

        // 1. Ubah status transaksi di tb_sewa menjadi 'Selesai'
        String sqlUpdateSewa = "UPDATE tb_sewa SET status_sewa = 'Selesai' WHERE id_sewa = '" + idSewa + "'";
        Core.DML.EQuery(sqlUpdateSewa);

        // 2. Ubah status kendaraan di tb_kendaraan kembali menjadi 'Tersedia'
        String sqlUpdateKendaraan = "UPDATE tb_kendaraan SET status = 'Tersedia' WHERE nopol = '" + nopol + "'";
        Core.DML.EQuery(sqlUpdateKendaraan);

        JOptionPane.showMessageDialog(this, "Pengembalian Kendaraan Berhasil Diproses!");

        // Reset inputan & Refresh isi tabel
        txtIdTransaksi.setText("");
        txtDenda.setText("0");
        tampilTable();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memproses pengembalian: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnProsesActionPerformed

    private void tbPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPengembalianMouseClicked
    int row = tbPengembalian.getSelectedRow();
    if (row != -1) {
        try {
            String idSewa = tbPengembalian.getValueAt(row, 0).toString();
            String tglSewaStr = tbPengembalian.getValueAt(row, 3).toString();
            int durasi = Integer.parseInt(tbPengembalian.getValueAt(row, 4).toString());
            int totalHarga = Integer.parseInt(tbPengembalian.getValueAt(row, 5).toString());

            // 1. Masukkan ID Transaksi ke kotak input
            txtIdTransaksi.setText(idSewa);

            // 2. Hitung Denda Otomatis (Jika Keterlambatan Terjadi)
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date tglSewa = sdf.parse(tglSewaStr);

            Calendar cal = Calendar.getInstance();
            cal.setTime(tglSewa);
            cal.add(Calendar.DAY_OF_MONTH, durasi);
            Date tglJatuhTempo = cal.getTime();

            Date tglHariIni = new Date();

            if (tglHariIni.after(tglJatuhTempo)) {
                long selisihMillis = tglHariIni.getTime() - tglJatuhTempo.getTime();
                long hariTerlambat = selisihMillis / (1000 * 60 * 60 * 24);

                int hargaPerHari = totalHarga / durasi;
                int denda = (int) (hariTerlambat * hargaPerHari);

                txtDenda.setText(String.valueOf(denda));
            } else {
                txtDenda.setText("0");
            }

        } catch (Exception e) {
            txtDenda.setText("0");
        }
    }    // TODO add your handling code here:
    }//GEN-LAST:event_tbPengembalianMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblIDTrk;
    private javax.swing.JTable tbPengembalian;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtIdTransaksi;
    // End of variables declaration//GEN-END:variables
}
