/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Desain;

/**
 *
 * @author DIKA
 */
public class FrPelanggan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrPelanggan
     */
    public FrPelanggan() {
        initComponents();
    // 1. HILANGKAN HEADER ABU-ABU & IKON PANAH
    javax.swing.plaf.basic.BasicInternalFrameUI ui = 
        (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
    ui.setNorthPane(null);

    // 2. HILANGKAN BORDER/GARIS PINGGIR ABU-ABU
    this.setBorder(null);

    // 3. TAMBAHKAN MARGIN BAWAH (Atas: 0, Kiri: 0, Bawah: 35px, Kanan: 0)
    ((javax.swing.JComponent) getContentPane()).setBorder(
        javax.swing.BorderFactory.createEmptyBorder(0, 0, 20, 0)
    );

    // 4. SET WARNA BACKGROUND TOSKA
    this.getContentPane().setBackground(new java.awt.Color(0, 210, 196));

    // 5. SAMAKAN DENGAN FrKendaraan: PAKSA MELEBAR MEMENUHI AREA
    try {
        this.setMaximum(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
    tampilTable();
        
        tampilTable();
        this.getContentPane().setBackground(new java.awt.Color(0, 210, 196));
        // KUNCI SIMETRIS: Memberi margin dalam (Atas: 15px, Kiri: 20px, Bawah: 25px, Kanan: 20px)
    ((javax.swing.JComponent) getContentPane()).setBorder(
        javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 20)
    );
        try {
        this.setMaximum(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
    }
    private void tampilTable() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("NIK");
        model.addColumn("Nama Pelanggan");
        model.addColumn("No. Telepon");
        model.addColumn("Alamat");
        
        try {
            java.sql.Connection conn = new myConnection.DB0().getConnection();
            java.sql.Statement st = conn.createStatement();
            String sql = "SELECT * FROM tb_pelanggan";
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nik"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("no_telp"),
                    rs.getString("alamat")
                });
            }
            tbPelanggan.setModel(model); // Sesuaikan dengan nama variabel tabel di Design Anda
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNik = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPelanggan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(850, 500));

        txtNik.addActionListener(this::txtNikActionPerformed);

        jLabel1.setText("NIK  :");

        jLabel2.setText("Nama :");

        jLabel3.setText("No. Telp :");

        jLabel4.setText("Alamat  :");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        tbPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPelanggan);

        jPanel1.setOpaque(false);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear);

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel1.add(btnHapus);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel1.add(btnUpdate);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        jPanel1.add(btnSimpan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNik, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTelp)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNikActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
try {
    if (txtNik.getText().isEmpty() || txtNama.getText().isEmpty() || txtTelp.getText().isEmpty() || txtAlamat.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua data harus diisi terlebih dahulu!");
        return;
    }

    String sql = "INSERT INTO tb_pelanggan (nik, nama_pelanggan, no_telp, alamat) VALUES ('" 
            + txtNik.getText() + "', '" 
            + txtNama.getText() + "', '" 
            + txtTelp.getText() + "', '" 
            + txtAlamat.getText() + "')";
    
    int i = Core.DML.EQuery(sql);
    
    if (i > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data Pelanggan Berhasil Disimpan!");
        txtNik.setText("");
        txtNama.setText("");
        txtTelp.setText("");
        txtAlamat.setText("");
        txtNik.setEnabled(true);
        tampilTable(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data! (Kemungkinan NIK sudah terdaftar)");
    }
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tbPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPelangganMouseClicked
try {
    int baris = tbPelanggan.getSelectedRow();
    if (baris != -1) {
        txtNik.setText(tbPelanggan.getValueAt(baris, 0).toString());
        txtNama.setText(tbPelanggan.getValueAt(baris, 1).toString());
        txtTelp.setText(tbPelanggan.getValueAt(baris, 2).toString());
        txtAlamat.setText(tbPelanggan.getValueAt(baris, 3).toString());
        
        // Kunci NIK agar primary key tidak bisa diubah saat mode update
        txtNik.setEnabled(false); 
    }
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_tbPelangganMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
try {
        if (txtNik.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pelanggan dari tabel!");
            return;
        }

        String sql = "UPDATE tb_pelanggan SET nama = '" + txtNama.getText() 
                + "', no_telp = '" + txtTelp.getText() 
                + "', alamat = '" + txtAlamat.getText() 
                + "' WHERE nik = '" + txtNik.getText() + "'";

        Core.DML.EQuery(sql);
        javax.swing.JOptionPane.showMessageDialog(this, "Data Pelanggan Berhasil Diubah!");
        
        btnClearActionPerformed(evt);
        tampilTable();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    txtNik.setText("");
    txtNama.setText("");
    txtTelp.setText("");
    txtAlamat.setText("");
    txtNik.setEditable(true);
    tbPelanggan.clearSelection();  // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
     try {
        if (txtNik.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pelanggan dari tabel!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus data pelanggan ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM tb_pelanggan WHERE nik = '" + txtNik.getText() + "'";
            Core.DML.EQuery(sql);
            javax.swing.JOptionPane.showMessageDialog(this, "Data Pelanggan Berhasil Dihapus!");
            
            btnClearActionPerformed(evt);
            tampilTable();
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbPelanggan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
