/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Desain;

public class FrRiwayat extends javax.swing.JInternalFrame {

    public FrRiwayat() {
        initComponents();
    Desain.FormUtils.formatFrame(this);
    // 1. HILANGKAN HEADER ABU-ABU & IKON PANAH
    javax.swing.plaf.basic.BasicInternalFrameUI ui = 
        (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
    ui.setNorthPane(null);
    ((javax.swing.JComponent) getContentPane()).setBorder(
        javax.swing.BorderFactory.createEmptyBorder(15, 20, 25, 20)
    );

    // 2. HILANGKAN BORDER/GARIS PINGGIR ABU-ABU
    this.setBorder(null);

    // Kode warna & tampil tabel yang sudah ada sebelumnya
    this.getContentPane().setBackground(new java.awt.Color(0, 210, 196));
        
        // Panggil dengan 2 parameter saat pertama kali buka form
        tampilTable("", "Semua");
        
        this.getContentPane().setBackground(new java.awt.Color(0, 210, 196));
        try {
            this.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }

    // PASTIKAN DI SINI ADA 2 PARAMETER: (String keyword, String statusFilter)
    private void tampilTable(String keyword, String statusFilter) {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Sewa");
        model.addColumn("NIK");
        model.addColumn("Nopol");
        model.addColumn("Tgl Sewa");
        model.addColumn("Durasi");
        model.addColumn("Total Harga");
        model.addColumn("Status");

        try {
            java.sql.Connection conn = new myConnection.DB0().getConnection();
            java.sql.Statement st = conn.createStatement();

            String sql = "SELECT * FROM tb_sewa WHERE (id_sewa LIKE '%" + keyword + "%' OR nik LIKE '%" + keyword + "%' OR nopol LIKE '%" + keyword + "%')";

            if (!statusFilter.equalsIgnoreCase("Semua")) {
                sql += " AND status_sewa = '" + statusFilter + "'";
            }

            sql += " ORDER BY tgl_sewa DESC";

            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_sewa"),
                    rs.getString("nik"),
                    rs.getString("nopol"),
                    rs.getString("tgl_sewa"),
                    rs.getString("durasi"),
                    "Rp " + rs.getString("total_harga"),
                    rs.getString("status_sewa")
                });
            }
            tbRiwayat.setModel(model);

        } catch (Exception e) {
            System.out.println("Gagal memuat data tabel: " + e.getMessage());
        }
    } // Kurung kurawal penutup method tampilTable

    // Method Cetak Laporan
    public void cetakLaporanPDF() {
    if (tbRiwayat.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Tidak ada data transaksi untuk dicetak!",
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Ambil data dari tbRiwayat
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbRiwayat.getModel();

    // Buka Popup Preview Laporan
    java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    Desain.FrPreview preview = new Desain.FrPreview(parent, model);
    preview.setVisible(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnCetakLaporan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRiwayat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();

        jLabel1.setText("Cari Data :");

        txtCari.addActionListener(this::txtCariActionPerformed);
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        btnCari.setText("CARI");
        btnCari.addActionListener(this::btnCariActionPerformed);

        btnCetakLaporan.setText("CETAK LAPORAN (PDF)");
        btnCetakLaporan.addActionListener(this::btnCetakLaporanActionPerformed);

        tbRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbRiwayat);

        jLabel2.setText("Status      :");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Sedang Disewa", "Selesai" }));

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCetakLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCari))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetakLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
     String keyword = txtCari.getText();
    String status = cbStatus.getSelectedItem().toString();
    tampilTable(keyword, status);   // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    txtCari.setText("");
    cbStatus.setSelectedIndex(0);
    tampilTable("", "Semua");    // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
    String keyword = txtCari.getText();
    String status = cbStatus.getSelectedItem().toString();
    tampilTable(keyword, status);    // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnCetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakLaporanActionPerformed
    cetakLaporanPDF();    // TODO add your handling code here:
    }//GEN-LAST:event_btnCetakLaporanActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetakLaporan;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbRiwayat;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
